config/routes.rb
Depot::Application.routes.draw do
  get "admin" => "admin#index"
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"
  
  get "store/mm"
  get "store/nn"
  post "store/donn"
  get "store/show"
  
  get "store/picture"
  get "store/xx"
  get "store/yy"
  get "store/zz"
  

  resources :products

   root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "depot", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="store">
	
	<div id="banner">
		<%= image_tag("logo.png") %>
		<%= @page_title || "我是默认标题" %>
	</div>
	
	<div id="columns">
		<div id="cart">
			<% if @cart %>
			<%= render @cart %>
			<% end %>
		</div>
		<div id="side">
			<a href="/">Home</a><br />
			<a href="/">Questions</a><br />
			<a href="/">News</a><br />
			<a href="/">Contact</a><br />
		</div>
		<% if session[:user_id] %>
			<br />
			<%= link_to 'Orders', orders_path %><br />
			<%= link_to 'Products', products_path %><br />
			<%= link_to 'Users', users_path %><br />
			<br />
			<%= button_to 'Logout', logout_path, :method => :delete %>
		<% end %>
		<div id="main">
			<%= yield :head %>
			<%= yield %>
		</div>
	</div>
	
</body>
</html>